### ISSUE TITLE
Lib math build errors 

### ISSUE THREAD

**Issue by drewwells** [moovweb/gosass#7]
Ldflags needs -lm when building on some architectures.  Sassc added this as well.  I can pr when I get on a computer.

**Comment by deepilla** [comment]
FYI I just came across this same issue while trying to `go get` gosass:

```
/usr/bin/ld: ../../../../../clibs/lib/libsass.a(eval.o): undefined reference to symbol 'fmod@@GLIBC_2.2.5'
/usr/lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Accepting the PR from drewwells would definitely make gosass easier to install. Unless there's another workaround...?

**Comment by drewwells** [comment]
By the way, I've created a wrapper for libsass. This might serve you needs https://github.com/wellington/go-libsass

**Comment by deepilla** [comment]
So far gosass seems to be working. I just came here to report the build issue (only to find that it had already been reported, just not fixed).
